name: Keep Discord Bot Alive

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run Discord bot
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      run: |
        npm start &
        sleep 300  # Keep running for 5 minutes
        echo "Session completed"
